lab1
Hreaun/Net_lab1 pull request #1
Opened 2020-09-16 15:00 UTC by Hreaun

2020-09-21 12:16 UTC, Aloomenon requested changes

2020-09-21 12:16 UTC, Aloomenon commented on src/main/java/Client.java
> +        socketOut = new DatagramSocket();
Сокеты открываются, а почему не закрываем?
Объясните что такое сокет, зачем ему порт и как с ними нужно работать.

2020-09-22 11:28 UTC, Hreaun commented on src/main/java/Client.java
> +        socketOut = new DatagramSocket();
@Aloomenon,
Сокет - это одна из конечных точек двустороннего канала связи между двумя программами, работающими в сети. Сокет привязан к номеру порта, чтобы уровень TCP мог идентифицировать приложение, в которое должны быть отправлены данные.

Для связи по TCP клиентская программа и серверная программа устанавливают соединение друг с другом. Каждая программа привязывает сокет к своему концу соединения. Для связи клиент и сервер каждый читает и записывает в сокет, привязанный к соединению.

Для работы с TCP соединением:
1. Открыть сокет (у клиента создать объект типа Socket, передав ему адрес и порт сервера; у сервера создать объект типа ServerSocket с портом, который он будет слушать).
2. Открыть входной поток и выходной поток в сокет.
3. Читать из потока и записывать в поток в соответствии с протоколом сервера.
4. Закрыть потоки.
5. Закрыть сокеты.

При использовании UDP адрес и порт получателя указываются в DatagramPacket, который затем отправляется через DatagramSocket. 

Если не закрыть сокет, в программе будет утечка файлового дескриптора. Программы могут открывать только ограниченное количество файловых дескрипторов, поэтому, если это происходит часто, система не сможет выделить фд другим программам.

Если сокет является TCP-сокетом и он подключен, то TCP-соединение не будет закрыто, пока сокет не будет закрыт.

2020-09-24 15:45 UTC, Aloomenon commented on src/main/java/Client.java
> +        socketOut = new DatagramSocket();
ок пойдет. Принял.

2020-09-24 15:45 UTC, Aloomenon approved these changes

2020-09-25 06:26 UTC, merged